theme: minima
title: Loukili Abdeslam Personal Website
author: @el-ouakili
email: abdeslam.loukili@etu.uae.ac.ma
description: > # this means to ignore newlines until "baseurl:"
  IT student who likes cybersecurity and hopes to be an ethical hacker someday!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
